language: python
python:
  - "2.7"
install:
    - pip install -Ur requirements.txt
    - pip install -Ur tests/requirements.txt
script:
    - python -m unittest discover

notifications:
  email: false
